project:
  shorten_stack_name: true
  name: quickstart-freeradius-mfa-workspaces
  owner: workspace@example.com
  package_lambda: false
  regions:
  - us-west-2
  - us-east-1
  template: ./templates/ws-main-2.template.yaml
  s3_regional_buckets:  true
tests:
  SC1:
    parameters:
      ADServer1InstanceType: t3.large
      ADServer1NetBIOSName: DC1
      ADServer1PrivateIP: 10.0.0.10
      ADServer2NetBIOSName: DC2
      ADServer2PrivateIP: 10.0.32.10
      AvailabilityZones: us-west-2a,us-west-2b
      DomainAdminPassword: $[taskcat_genpass_16]
      DomainAdminUser: Admin
      DomainDNSName: funfactory.com
      DomainNetBIOSName: funfactory
      KeyPairName: taskcatTest
      NumberOfRDGWHosts: '0'
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      RDGWInstanceType: t2.large
      RDGWCIDR: 10.0.0.0/16
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-freeradius-mfa-workspaces/
      PKI: 'No'
      EntCaServerInstanceType: t3.large
      EntCaDataDriveSizeGiB: '2'
      EntCaServerNetBIOSName: 'EntCa1'
      EntCaKeyLength: '2048'
      EntCaHashAlgorithm: 'SHA256'
      EntCaValidityPeriodUnits: '5'
      CreateDefaultOUs: 'Yes'
      TombstoneLifetime: '60'
      DeletedObjectLifetime: '60'
      DHCPOptionSet: 'Yes'
      LinOTPAdminPassword: $[taskcat_genpass_16]
      LinOTPDBName: LINOTP
      LinOTPReamlName: MyADRealm
      EnableSelfService: 'true'
      EnableWorkDocs: 'false'
    regions:
    - us-west-2
    template: ./templates/ws-main-1.template.yaml
  SC2:
    parameters:
      AvailabilityZones: us-east-1b,us-east-1c
      DomainAdminPassword: $[taskcat_genpass_16]
      DomainAdminUser: Admin
      DomainDNSName: nbafinals.com
      DomainNetBIOSName: nbafinals
      KeyPairName: taskcatTest
      NumberOfRDGWHosts: '0'
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      RDGWInstanceType: t2.large
      RDGWCIDR: 10.0.0.0/16
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-freeradius-mfa-workspaces/
      PKI: 'No'
      EntCaServerInstanceType: t3.large
      EntCaDataDriveSizeGiB: '2'
      EntCaServerNetBIOSName: 'EntCa1'
      EntCaKeyLength: '2048'
      EntCaHashAlgorithm: 'SHA256'
      EntCaValidityPeriodUnits: '5'
      CreateDefaultOUs: 'Yes'
      TombstoneLifetime: '60'
      DeletedObjectLifetime: '60'
      DHCPOptionSet: 'Yes'
      LinOTPAdminPassword: $[taskcat_genpass_16]
      LinOTPDBName: LINOTP
      LinOTPReamlName: MyADRealm
      EnableSelfService: 'true'
      EnableWorkDocs: 'false'
    regions:
    - us-east-1
    template: ./templates/ws-main-2.template.yaml
